import { Inter } from "next/font/google";
import "@/app/globals.css";
import Script from "next/script";
import dynamic from "next/dynamic";
// import { GoogleAnalytics } from "@next/third-parties/google";
// import { analytics } from "@/utils/envVariables";

const Footer = dynamic(() => import("@/components/Footer/Footer"));

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Neechem Industries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="bg-themebackground flex flex-col min-h-screen w-full items-center overflow-hidden relative">
            <main className="flex-1 w-full overflow-x-hidden mb-5 max-w-[1600px] pt-[80px]">
              {children}
            </main>
            <Footer />
            <p className="w-full text-center font-roboto text-sm m-2">
              © {new Date().getFullYear()} Neechem Industries. All Rights
              Reserved.
            </p>
          </div>
      </body>
      {/* <GoogleAnalytics gaId={analytics} /> */}
    </html>
  );
}