import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer/Footer";

const SideBar = dynamic(() => import("@/components/Sidebar/Sidebar"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="overflow-hidden flex flex-col min-h-screen">
            <main className="flex flex-1 w-screen bg-themebackground">
              <SideBar />
              <div className="flex flex-col flex-1">
                {/* <header className="sticky top-0 w-full !pl-[0.8rem] !pr-[0.8rem] md:!pl-[1.5rem] md:!pr-[1.5rem] z-9 flex justify-center"></header> */}
                <div className="flex-1 w-full pl-[0.8rem] pr-[1rem] md:!pl-[1.5rem] md:pr-[3rem] overflow-y-auto">
                  {children}
                </div>
              </div>
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
